# Generated by Django 3.2.3 on 2021-06-04 09:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Item', models.CharField(max_length=30)),
                ('Title', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=250)),
                ('Title', models.TextField()),
                ('Priority', models.CharField(choices=[('T', 'Top'), ('H', 'Hight'), ('N', 'Normal'), ('L', 'Low')], default='T', max_length=2)),
                ('Status', models.CharField(choices=[('P', 'Planned'), ('I', 'In work'), ('Pr', 'Procrastinate'), ('O', 'Outstanding'), ('C', 'Closed'), ('D', 'Deleted')], default='P', max_length=2)),
                ('Date_create', models.DateTimeField(default=django.utils.timezone.now)),
                ('Date_start', models.DateTimeField()),
                ('Date_end', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Item', models.CharField(max_length=30)),
                ('Title', models.CharField(max_length=250)),
            ],
        ),
    ]
