# Generated by Django 3.2.3 on 2021-06-04 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Goals', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='Title',
        ),
        migrations.AddField(
            model_name='category',
            name='Help_text',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
