# Generated by Django 3.2.3 on 2021-06-04 10:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Goals', '0006_alter_goal_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='goal',
            name='Category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Goals.category'),
        ),
        migrations.AddField(
            model_name='goal',
            name='Group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Goals.group'),
        ),
    ]
