# Generated by Django 3.2.3 on 2021-06-04 10:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Goals', '0007_auto_20210604_1304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goal',
            name='Category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Goals.category'),
        ),
        migrations.AlterField(
            model_name='goal',
            name='Group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Goals.group'),
        ),
    ]
