# Generated by Django 3.2.4 on 2021-06-22 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Goals', '0009_auto_20210604_1601'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goal',
            name='Date_create',
            field=models.DateField(auto_now_add=True),
        ),
    ]
